### ISSUE TITLE
Deleting Single Record in History removes all records

### ISSUE THREAD

**Issue by mhmzdev** [m-hamzashakeel/Discount-Calculator-React-Native#5]
If there are multiple records in history.  Then by `tapping` a single record removes full list. If you go on previous screen and come back the list appears and that specific item is deleted.

File(s) to be considered
- `./components/History.js`

### Demonstration

https://user-images.githubusercontent.com/43790152/102691665-dfc41d80-422f-11eb-8f50-aa935f5f3276.mp4

**Comment by haseebalisajid** [comment]
you can use filter method to remove a single record in a list
const removeRecord = (itemID) => {
    setDataObj((currentItems) => {
      return currentItems.filter((item) => item.id !== itemID);
    });
  };
itemID is the id of that particular item you want to delete .
